POST http://localhost:3001/api/blogs/5d515ce761f6fc41267f219c/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdlbmVyaWNfdXNlcm5hbWUiLCJpZCI6IjVkMmQ5YWQ0MjBhNzdiNWI2MDVmMjFiZiIsImlhdCI6MTU2MzM3MDUzM30.rzW8ASaQY6tNhhYqtDiBVoNBUUnT3mH6B63VYiOqPME

{
    "comment": "this is another comment"
}